name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'task-*' # Trigger on pushes to main and any task branch
  pull_request:
    branches:
      - main
      - 'task-*' # Trigger on pull requests to main and any task branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use a standard Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to check out your repository

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Or your preferred Python version (e.g., '3.10', '3.11')

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Install all packages from your requirements.txt

    - name: Run Linter (Pylint)
      run: |
        pylint --fail-under=7.0 $(find . -name "*.py" ! -path "./.venv/*") || true # Lint all Python files, allowing pipeline to pass even if linting score is low.
        # Adjust '7.0' to your desired minimum Pylint score. Remove '|| true' to make it fail the workflow.
        # You might want to exclude certain directories like '.venv/' or 'data_storage/'

    - name: Check for reproducible DVC data (Optional, advanced for later)
      run: |
        # This step checks if DVC data can be reproduced.
        # It requires DVC to be fully set up and data tracked.
        # You might want to uncomment this later in the project.
        # dvc pull || true # Pull data from DVC remote (local in this case, might need special setup for GitHub Actions)
        echo "DVC data check skipped for initial setup. Implement once DVC is mature."

    # - name: Run Unit Tests (Optional)
    #   run: |
    #     # If you create a 'tests/' directory with test files (e.g., test_eda.py)
    #     # pip install pytest
    #     # pytest tests/

    - name: Verify project structure and basic files
      run: |
        ls -la
        test -f README.md # Check if README exists
        test -f requirements.txt # Check if requirements.txt exists
        echo "Basic file structure verified."